language: en
pipeline:
- name: ConveRTTokenizer  
- name: RegexFeaturizer
- name: EntitySynonymMapper
- name: ConveRTFeaturizer
- name: DIETClassifier
  BILOU_flag: False
  epochs: 50
  batch_size: 64
- name: ResponseSelector
  epochs: 200
policies:
- name: MemoizationPolicy
- name: EmbeddingPolicy
  max_history: 5
  batch_strategy: balanced
  epochs: 50
  random_seed: 666
  evaluate_on_num_examples: 0
- name: MappingPolicy
- name: FormPolicy
